Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Provisioning web and db server..."

  config.vm.define "web" do |web|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.56.3"
  end

  config.vm.define "db" do |db|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.56.2"
  end
end