---

- hosts: all
  become: true
  pre_tasks:

    - name: update repo cache (Ubuntu)
      tags: allways
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
    
    - name: generate ssh_config file from template
      tags: ssh
      template:
        src: "{{ ssh_template_file }}"
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
      notify: restart_sshd

  handlers:
    - name: restart_sshd
      service:
        name: ssh
        state: restarted

- hosts: web
  become: true
  roles:
    - web

- hosts: db
  become: true
  roles:
    - db
    

    